---

- hosts: all
  become: true
  tasks:
    - name: Update Repository Index 
      yum: 
        update_cache: yes
    - name: Install Apache Server
      yum:
        name: httpd
        state: present
    - name: Start & Enable Service
      service: 
        name: httpd
        state: started
        enabled: yes
     
